#!/bin/bash

set -o errexit -o nounset -o pipefail

install_deps() {
  python3 -m pip install . coverage
}

run_tests() {
  cd test/core && PYTHONPATH=`pwd`/../../ python3 run_tests.py --num-parallel 8
}

install_deps && run_tests
