[tox]
envlist = unit
skipsdist = True

[testenv]
allowlist_externals = ./test_runner
commands = ./test_runner
passenv = *
deps =
    -e {toxinidir}[dev]

[testenv:unit]
commands = pytest test/unit/ test/cmd/ test/plugins/ --ignore=test/unit/spin -v --tb=short --timeout=120 {posargs}

[testenv:ux-local]
commands = pytest test/ux/core/ --only-backend local -n 4 -v --tb=short --timeout=1800 {posargs}

[testenv:ux-sfn]
commands = pytest test/ux/core/ --only-backend sfn-batch -n 4 -v --tb=short --timeout=1800 {posargs}

[testenv:ux-argo]
commands = pytest test/ux/core/ --only-backend argo-kubernetes -n 2 -v --tb=short --timeout=1800 {posargs}

[testenv:ux-airflow]
commands = pytest test/ux/core/ --only-backend airflow-kubernetes -n 2 -v --tb=short --timeout=1800 {posargs}
