"""
Metaflow orchestrator scaffolding tool.

Generates a complete orchestrator skeleton with all contract requirements
pre-filled and annotated.  This makes it hard to forget the requirements
that every orchestrator gets wrong the first time.

Usage:
    python -m metaflow.scaffold_orchestrator my_scheduler

This creates:
    ./my_scheduler_deployer.py   — DeployerImpl subclass
    ./my_scheduler_objects.py    — DeployedFlow / TriggeredRun subclass
    ./my_scheduler_cli.py        — CLI entry-point group
    ./ux-tests-my_scheduler.yml  — GitHub Actions workflow skeleton

The generated files compile without modification.  Replace every
TODO / FIXME comment with real implementation code.
"""

import os
import sys
import textwrap


# ---------------------------------------------------------------------------
# Template: deployer_impl subclass
# ---------------------------------------------------------------------------

_DEPLOYER_TEMPLATE = '''\
"""
{name} deployer implementation.

Generated by: python -m metaflow.scaffold_orchestrator {name}

Contract requirements (DO NOT remove these comments):
  1. run_params MUST be a list, not a tuple.
     Click returns tuples for multi-value options.  Always convert with list().
  2. --branch MUST be forwarded to every step subprocess.
     @project reads branch from --branch at step runtime, not just at compile time.
  3. METAFLOW_FLOW_CONFIG_VALUE MUST be injected into each step environment.
     @config and @project use this env var to reconstruct the config at task runtime.
  4. retry_count MUST be derived from the scheduler\'s native attempt number.
     DO NOT hardcode retry_count=0.
  5. All required Metaflow env vars MUST be present in the container environment.
     See REQUIRED_ENV_VARS below.
"""

import json
import os
from typing import ClassVar, Dict, List, Optional

from metaflow.runner.deployer_impl import DeployerImpl


# ---------------------------------------------------------------------------
# REQUIRED environment variables for Metaflow steps running inside containers.
# Every container the scheduler launches MUST have these set.
# ---------------------------------------------------------------------------
REQUIRED_ENV_VARS = {{
    # REQUIRED: Metaflow metadata service URL reachable from inside the container.
    "METAFLOW_SERVICE_URL": os.environ.get("METAFLOW_SERVICE_URL", ""),

    # REQUIRED: Internal URL used by step subprocesses (may differ from external URL).
    "METAFLOW_SERVICE_INTERNAL_URL": os.environ.get(
        "METAFLOW_SERVICE_INTERNAL_URL",
        os.environ.get("METAFLOW_SERVICE_URL", ""),
    ),

    # REQUIRED for @config/@project: serialized config dict injected at deploy time.
    # Extract from flow._flow_state[FlowStateItems.CONFIGS] and JSON-serialize.
    # Without this, tasks run with empty/default config and @project name is wrong.
    # See airflow_deployer.py for the reference implementation.
    "METAFLOW_FLOW_CONFIG_VALUE": "",  # TODO: populate from flow state at compile time
}}


class {classname}DeployerImpl(DeployerImpl):
    """
    Deployer implementation for {name}.

    Compiles the flow into a {name} workflow definition and submits it
    to the {name} scheduler.
    """

    TYPE: ClassVar[Optional[str]] = "{name}"

    def __init__(self, flow_file: str, **kwargs):
        super().__init__(flow_file, **kwargs)
        # TODO: add {name}-specific __init__ args here (e.g. host, namespace)

    @property
    def deployer_kwargs(self) -> Dict:
        # TODO: return the kwargs dict that maps to the {name} CLI group options
        return {{}}

    @staticmethod
    def deployed_flow_type():
        from .{name}_objects import {classname}DeployedFlow
        return {classname}DeployedFlow

    def create(self, **kwargs):
        return self._create(self.deployed_flow_type(), **kwargs)

    def _build_step_command(
        self,
        step_name: str,
        run_id: str,
        task_id: str,
        branch: Optional[str] = None,
        retry_count: int = 0,  # TODO: derive from scheduler attempt, NOT hardcoded
    ) -> List[str]:
        """
        Build the command list to execute one step.

        IMPORTANT: --branch MUST be included when branch is not None.
        @project reads branch_name from --branch at step runtime.
        Omitting --branch causes current.branch_name to be empty in all step tasks.

        IMPORTANT: retry_count MUST come from the scheduler\'s native attempt counter.
        For example:
            AWS Batch:   int(os.environ.get("AWS_BATCH_JOB_ATTEMPT", "0"))
            Kubernetes:  derived from pod restartCount or annotation
            Airflow:     context["ti"].try_number - 1
        DO NOT hardcode retry_count=0.
        """
        cmd = [
            "python",
            self.flow_file,
            "--quiet",
            "--metadata",
            "service",
            # REQUIRED for @project: branch must be forwarded to every step subprocess.
            # Without this, current.branch_name is empty inside the task.
        ]

        if branch:
            # REQUIRED for @project
            cmd += ["--branch", branch]

        cmd += [
            "step",
            step_name,
            "--run-id",
            run_id,
            "--task-id",
            task_id,
            "--retry-count",
            str(retry_count),  # TODO: replace with scheduler-native attempt number
        ]

        return cmd
'''


# ---------------------------------------------------------------------------
# Template: DeployedFlow / TriggeredRun objects
# ---------------------------------------------------------------------------

_OBJECTS_TEMPLATE = '''\
"""
{name} DeployedFlow and TriggeredRun objects.

Generated by: python -m metaflow.scaffold_orchestrator {name}
"""

from typing import Any, Dict, List, Optional

from metaflow.runner.deployer import DeployedFlow, TriggeredRun


class {classname}TriggeredRun(TriggeredRun):
    """Represents a single triggered execution of a {name} workflow."""

    @property
    def status(self) -> Optional[str]:
        """
        Return the current run status.

        MUST return one of: None, "RUNNING", "SUCCEEDED", "FAILED", "TIMED_OUT",
        "ABORTED" (case-insensitive check in wait_for_deployed_run).
        """
        # TODO: query {name} for the current execution status
        raise NotImplementedError

    def terminate(self, **kwargs) -> bool:
        """Terminate the running execution."""
        # TODO: call {name} API to stop the execution
        raise NotImplementedError


class {classname}DeployedFlow(DeployedFlow):
    """Represents a deployed {name} workflow (analogous to a DAG or state machine)."""

    def trigger(
        self,
        run_params: Optional[List[str]] = None,  # IMPORTANT: must be list, not tuple
        **kwargs: Any,
    ) -> {classname}TriggeredRun:
        """
        Trigger a new run of the deployed workflow.

        IMPORTANT: run_params MUST be a list, not a tuple.
        Click returns tuples for multi-value options; always ensure you convert:
            run_params = list(run_params) if run_params else []

        Args
        ----
        run_params : list of str, optional
            Runtime parameter overrides in the form ["param_name=value", ...].
            IMPORTANT: must be a list, not a tuple.
        """
        # IMPORTANT: must be list, not tuple
        run_params = list(run_params) if run_params else []

        # TODO: call {name} API to start a new execution, forwarding run_params
        raise NotImplementedError

    @classmethod
    def from_deployment(cls, identifier: str, **kwargs) -> "{classname}DeployedFlow":
        """
        Recover a previously deployed workflow by its identifier.

        Args
        ----
        identifier : str
            The workflow name / ARN / identifier returned by create().
            If the identifier is dotted (project.branch.FlowName), use only
            the last component as the flow class name to avoid SyntaxError.
            Example: identifier.split(".")[-1]
        """
        # TODO: look up the workflow and return a {classname}DeployedFlow
        raise NotImplementedError
'''


# ---------------------------------------------------------------------------
# Template: CLI entry point
# ---------------------------------------------------------------------------

_CLI_TEMPLATE = '''\
"""
{name} CLI group for Metaflow.

Generated by: python -m metaflow.scaffold_orchestrator {name}

Register this group in metaflow/plugins/__init__.py (DEPLOYER_PACKAGES_TRIE or
equivalent) so that `python flow.py {name} ...` works.
"""

import click


@click.group()
def cli():
    """Commands for managing {name} deployments."""
    pass


@cli.command()
@click.option("--tags", multiple=True, help="Tags to apply to the deployment.")
@click.option(
    "--deployer-attribute-file",
    default=None,
    help="Internal: path to write deployment attributes JSON.",
)
def create(tags, deployer_attribute_file):
    """Deploy the flow to {name}."""
    # TODO: compile workflow definition and submit to {name}
    # After successful deployment, write a JSON file to deployer_attribute_file
    # with at least: {{"name": "<workflow_id>", "flow_name": "<FlowClass>"}}
    raise NotImplementedError("create() not yet implemented")


@cli.command()
def delete():
    """Remove a {name} deployment."""
    raise NotImplementedError("delete() not yet implemented")


@cli.command()
def list():
    """List {name} deployments for this flow."""
    raise NotImplementedError("list() not yet implemented")
'''


# ---------------------------------------------------------------------------
# Template: GitHub Actions workflow
# ---------------------------------------------------------------------------

_GHA_TEMPLATE = """\
name: UX Tests — {name}

# Compliance and integration tests for the {name} orchestrator.
# Generated by: python -m metaflow.scaffold_orchestrator {name}
#
# Add this workflow to .github/workflows/ after wiring up the devstack.

on:
  push:
    branches:
      - master
      - "**/{name}/**"
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  ux-tests:
    name: "{name} UX tests"
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          # Runner (local) backend — always included
          - backend: local
            services: "minio,postgresql,metadata-service"
            workers: 4

          # {name} backend — add the services your scheduler needs
          - backend: {name}
            services: "minio,postgresql,metadata-service"  # TODO: add {name} service
            workers: 4

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install Metaflow and test dependencies
        run: |
          pip install --upgrade pip
          pip install -e ".[dev]" pytest-xdist pytest-timeout pytest-cov

      - name: Set up minikube
        uses: medyagh/setup-minikube@latest
        with:
          driver: docker
          cpus: 2
          memory: 6144

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Install Tilt
        run: |
          curl -fsSL https://raw.githubusercontent.com/tilt-dev/tilt/master/scripts/install.sh \\
            | VERSION=v0.33.11 bash

      - name: Start devstack
        working-directory: devtools
        run: |
          mkdir -p .devtools
          SERVICES="${{{{ matrix.services }}}}" \\
            tilt up --stream 2>&1 | tee /tmp/tilt.log &
          for i in $(seq 1 60); do
            tilt get session >/dev/null 2>&1 && break
            sleep 2
          done
          tilt wait --for=condition=Ready "uiresource/(Tiltfile)" --timeout=120s
          tilt wait --for=condition=Ready uiresource/generate-configs --timeout=1800s

      - name: Start minikube tunnel
        run: sudo minikube tunnel &

      - name: Run compliance tests — ${{{{ matrix.backend }}}}
        run: |
          AWS_SHARED_CREDENTIALS_FILE="" \\
          PYTHONPATH=$PWD \\
          python -m pytest \\
            test/ux/core/test_compliance.py \\
            test/ux/core/test_basic.py \\
            test/ux/core/test_config.py \\
            test/ux/core/test_dag.py \\
            -m "not conda" \\
            --only-backend "${{{{ matrix.backend }}}}" \\
            -n ${{{{ matrix.workers }}}} \\
            -v \\
            --tb=short \\
            --timeout=1800 \\
            --cov=metaflow \\
            --cov-report=xml:coverage.xml \\
            --junit-xml=junit-${{{{ matrix.backend }}}}.xml

      - name: Upload coverage
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{{{ matrix.backend }}}}
          path: coverage.xml
          if-no-files-found: ignore
          include-hidden-files: true

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: junit-${{{{ matrix.backend }}}}
          path: junit-${{{{ matrix.backend }}}}.xml
          if-no-files-found: ignore
"""


# ---------------------------------------------------------------------------
# Generator
# ---------------------------------------------------------------------------


def _classname(name: str) -> str:
    """Convert snake_case or kebab-case to PascalCase."""
    return "".join(part.capitalize() for part in name.replace("-", "_").split("_"))


def _write(path: str, content: str) -> None:
    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w") as f:
        f.write(content)
    print(f"  wrote {path}")


def scaffold(name: str, output_dir: str = ".") -> None:
    cls = _classname(name)

    files = {
        f"{name}_deployer.py": _DEPLOYER_TEMPLATE.format(name=name, classname=cls),
        f"{name}_objects.py": _OBJECTS_TEMPLATE.format(name=name, classname=cls),
        f"{name}_cli.py": _CLI_TEMPLATE.format(name=name, classname=cls),
        f"ux-tests-{name}.yml": _GHA_TEMPLATE.format(name=name, classname=cls),
    }

    print(f"Scaffolding orchestrator: {name!r} (class prefix: {cls})")
    for filename, content in files.items():
        _write(os.path.join(output_dir, filename), content)

    print()
    print("Next steps:")
    print(f"  1. Implement TODO sections in {name}_deployer.py and {name}_objects.py")
    print(f"  2. Register the CLI group in metaflow/plugins/__init__.py")
    print(f"  3. Add a backend entry to test/ux/ux_test_config.yaml")
    print(f"  4. Run the compliance tests:")
    print(
        f"     python -m pytest test/ux/core/test_compliance.py "
        f"--only-backend {name} -v"
    )
    print()
    print("Contract checklist (things every orchestrator gets wrong):")
    print("  [ ] run_params is a list (not a tuple) in trigger()")
    print("  [ ] --branch forwarded to every step subprocess")
    print("  [ ] METAFLOW_FLOW_CONFIG_VALUE injected into container env")
    print("  [ ] retry_count derived from scheduler native attempt number")
    print("  [ ] All REQUIRED_ENV_VARS populated at step launch time")


def main():
    if len(sys.argv) < 2:
        print(__doc__)
        print("Usage: python -m metaflow.scaffold_orchestrator <name>")
        sys.exit(1)

    name = sys.argv[1].replace("-", "_")
    output_dir = sys.argv[2] if len(sys.argv) > 2 else "."
    scaffold(name, output_dir)


if __name__ == "__main__":
    main()
