apiVersion: v1
kind: Secret
metadata:
  name: minio-secret
type: Opaque
stringData:
  AWS_ACCESS_KEY_ID: rootuser
  AWS_SECRET_ACCESS_KEY: rootpass123
  AWS_ENDPOINT_URL_S3: http://minio.default.svc.cluster.local:9000
