"""
Python-native context definitions for the Metaflow core test suite.

Supersedes contexts.json as the authoritative source. run_tests.py still
reads contexts.json for its standalone debug CLI; conftest.py and
test_core_pytest.py import from this module.
"""

_SASHIMI = "刺身 means sashimi"

_COMMON_TOP_LOCAL = [
    "--metadata=local",
    "--datastore=local",
    "--environment=local",
    "--event-logger=nullSidecarLogger",
    "--no-pylint",
    "--quiet",
]
_COMMON_RUN_OPTIONS = [
    "--max-workers=50",
    "--max-num-splits=10000",
    "--tag=%s" % _SASHIMI,
    "--tag=multiple tags should be ok",
]
_DISABLED_LOCAL = [
    "LargeArtifactTest",
    "S3FailureTest",
    "CardComponentRefreshTest",
    "CardWithRefreshTest",
]
_DISABLED_CLOUD = [
    "LargeArtifactTest",
    "WideForeachTest",
    "TagCatchTest",
    "BasicUnboundedForeachTest",
    "NestedUnboundedForeachTest",
    "DetectSegFaultTest",
    "TimeoutDecoratorTest",
    "CardExtensionsImportTest",
    "RunIdFileTest",
]
_DISABLED_SCHEDULER = _DISABLED_CLOUD + [
    "CardComponentRefreshTest",
    "CardWithRefreshTest",
]

# Each entry is a dict compatible with the format run_tests.py expects.
ALL_CONTEXTS = [
    {
        "name": "python3-all-local",
        "disabled": False,
        "python": "python3",
        "env": {
            "METAFLOW_USER": "tester",
            "METAFLOW_RUN_BOOL_PARAM": "False",
            "METAFLOW_RUN_NO_DEFAULT_PARAM": "test_str",
            "METAFLOW_DEFAULT_METADATA": "local",
        },
        "top_options": _COMMON_TOP_LOCAL,
        "run_options": _COMMON_RUN_OPTIONS,
        "checks": ["python3-cli", "python3-metadata"],
        "disabled_tests": _DISABLED_LOCAL,
        "executors": ["cli", "api"],
    },
    {
        "name": "python3-all-local-cards-realtime",
        "disabled": True,
        "python": "python3",
        "env": {
            "METAFLOW_USER": "tester",
            "METAFLOW_RUN_BOOL_PARAM": "False",
            "METAFLOW_RUN_NO_DEFAULT_PARAM": "test_str",
            "METAFLOW_DEFAULT_METADATA": "local",
        },
        "top_options": _COMMON_TOP_LOCAL,
        "run_options": _COMMON_RUN_OPTIONS,
        "checks": ["python3-cli", "python3-metadata"],
        "enabled_tests": ["CardComponentRefreshTest", "CardWithRefreshTest"],
        "executors": ["cli", "api"],
    },
    {
        "name": "python3-all-local-azure-storage",
        "disabled": False,
        "python": "python3",
        "env": {
            "METAFLOW_USER": "tester",
            "METAFLOW_RUN_BOOL_PARAM": "False",
            "METAFLOW_RUN_NO_DEFAULT_PARAM": "test_str",
            "METAFLOW_DEFAULT_METADATA": "local",
            "METAFLOW_DEFAULT_DATASTORE": "azure",
            "METAFLOW_DATASTORE_SYSROOT_AZURE": "az://metaflow-test/metaflow/{nonce}",
            "METAFLOW_AZURE_STORAGE_BLOB_SERVICE_ENDPOINT": "http://127.0.0.1:10000/devstoreaccount1",
            "AZURE_STORAGE_CONNECTION_STRING": (
                "DefaultEndpointsProtocol=http;"
                "AccountName=devstoreaccount1;"
                "AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;"
                "BlobEndpoint=http://127.0.0.1:10000/devstoreaccount1;"
            ),
        },
        "top_options": [
            "--metadata=local",
            "--datastore=azure",
            "--environment=local",
            "--event-logger=nullSidecarLogger",
            "--no-pylint",
            "--quiet",
        ],
        "run_options": _COMMON_RUN_OPTIONS,
        "checks": ["python3-cli", "python3-metadata"],
        "disabled_tests": _DISABLED_LOCAL,
        "executors": ["cli", "api"],
    },
    {
        "name": "python3-all-local-gcs",
        "disabled": False,
        "python": "python3",
        "env": {
            "METAFLOW_USER": "tester",
            "METAFLOW_RUN_BOOL_PARAM": "False",
            "METAFLOW_RUN_NO_DEFAULT_PARAM": "test_str",
            "METAFLOW_DEFAULT_METADATA": "local",
            "METAFLOW_DEFAULT_DATASTORE": "gs",
            "METAFLOW_DATASTORE_SYSROOT_GS": "gs://metaflow-test/metaflow/{nonce}",
            "STORAGE_EMULATOR_HOST": "http://localhost:4443",
        },
        "top_options": [
            "--metadata=local",
            "--datastore=gs",
            "--environment=local",
            "--event-logger=nullSidecarLogger",
            "--no-pylint",
            "--quiet",
        ],
        "run_options": _COMMON_RUN_OPTIONS,
        "checks": ["python3-cli", "python3-metadata"],
        "disabled_tests": _DISABLED_LOCAL,
        "executors": ["cli", "api"],
    },
    {
        "name": "dev-local",
        "disabled": True,
        "python": "python3",
        "env": {
            "METAFLOW_USER": "tester",
            "METAFLOW_RUN_BOOL_PARAM": "False",
            "METAFLOW_RUN_NO_DEFAULT_PARAM": "test_str",
            "METAFLOW_DEFAULT_METADATA": "local",
        },
        "top_options": _COMMON_TOP_LOCAL,
        "run_options": _COMMON_RUN_OPTIONS,
        "checks": ["python3-cli", "python3-metadata"],
        "disabled_tests": ["S3FailureTest"],
        "executors": ["cli", "api"],
    },
    {
        "name": "python3-batch",
        "disabled": False,
        "disable_parallel": True,
        "python": "python3",
        "env": {
            "METAFLOW_USER": "tester",
            "METAFLOW_RUN_BOOL_PARAM": "False",
            "METAFLOW_RUN_NO_DEFAULT_PARAM": "test_str",
            "METAFLOW_DEFAULT_METADATA": "service",
            "METAFLOW_SERVICE_URL": "http://localhost:8080",
            "METAFLOW_DEFAULT_DATASTORE": "s3",
            "METAFLOW_DATASTORE_SYSROOT_S3": "s3://metaflow-test/metaflow/{nonce}",
            "METAFLOW_BATCH_JOB_QUEUE": "localbatch-default",
            "METAFLOW_BATCH_CLIENT_PARAMS": '{"endpoint_url":"http://localhost:8000"}',
            "AWS_ACCESS_KEY_ID": "rootuser",
            "AWS_SECRET_ACCESS_KEY": "rootpass123",
            "AWS_ENDPOINT_URL_S3": "http://localhost:9000",
            "AWS_DEFAULT_REGION": "us-east-1",
        },
        "top_options": [
            "--metadata=service",
            "--event-logger=nullSidecarLogger",
            "--no-pylint",
            "--quiet",
            "--with=batch",
            "--datastore=s3",
        ],
        "run_options": _COMMON_RUN_OPTIONS,
        "checks": ["python3-cli", "python3-metadata"],
        "disabled_tests": _DISABLED_CLOUD,
        "executors": ["cli", "api"],
    },
    {
        "name": "python3-k8s",
        "disabled": False,
        "disable_parallel": True,
        "python": "python3",
        "env": {
            "METAFLOW_USER": "tester",
            "METAFLOW_RUN_BOOL_PARAM": "False",
            "METAFLOW_RUN_NO_DEFAULT_PARAM": "test_str",
            "METAFLOW_DEFAULT_METADATA": "service",
            "METAFLOW_SERVICE_URL": "http://localhost:8080",
            "METAFLOW_SERVICE_INTERNAL_URL": "http://metaflow-service.default.svc.cluster.local:8080",
            "METAFLOW_DEFAULT_DATASTORE": "s3",
            "METAFLOW_DATASTORE_SYSROOT_S3": "s3://metaflow-test/metaflow/{nonce}",
            "METAFLOW_KUBERNETES_NAMESPACE": "default",
            "METAFLOW_KUBERNETES_SECRETS": "minio-secret",
            "AWS_ACCESS_KEY_ID": "rootuser",
            "AWS_SECRET_ACCESS_KEY": "rootpass123",
            "AWS_ENDPOINT_URL_S3": "http://localhost:9000",
            "AWS_DEFAULT_REGION": "us-east-1",
        },
        "top_options": [
            "--metadata=service",
            "--event-logger=nullSidecarLogger",
            "--no-pylint",
            "--quiet",
            "--with=kubernetes:memory=256,disk=1024",
            "--datastore=s3",
        ],
        "run_options": _COMMON_RUN_OPTIONS,
        "checks": ["python3-cli", "python3-metadata"],
        "disabled_tests": _DISABLED_CLOUD,
        "executors": ["cli", "api"],
    },
    {
        "name": "python3-argo-workflows",
        "disabled": False,
        "disable_parallel": True,
        "scheduler": "argo-workflows",
        "scheduler_timeout": 600,
        "python": "python3",
        "env": {
            "METAFLOW_USER": "tester",
            "METAFLOW_RUN_BOOL_PARAM": "False",
            "METAFLOW_RUN_NO_DEFAULT_PARAM": "test_str",
            "METAFLOW_DEFAULT_METADATA": "service",
            "METAFLOW_SERVICE_URL": "http://localhost:8080",
            "METAFLOW_SERVICE_INTERNAL_URL": "http://metaflow-service.default.svc.cluster.local:8080",
            "METAFLOW_DEFAULT_DATASTORE": "s3",
            "METAFLOW_DATASTORE_SYSROOT_S3": "s3://metaflow-test/metaflow/{nonce}",
            "METAFLOW_KUBERNETES_NAMESPACE": "default",
            "METAFLOW_KUBERNETES_SECRETS": "minio-secret",
            "AWS_ACCESS_KEY_ID": "rootuser",
            "AWS_SECRET_ACCESS_KEY": "rootpass123",
            "AWS_ENDPOINT_URL_S3": "http://localhost:9000",
            "AWS_DEFAULT_REGION": "us-east-1",
        },
        "top_options": [
            "--metadata=service",
            "--event-logger=nullSidecarLogger",
            "--no-pylint",
            "--quiet",
            "--datastore=s3",
        ],
        "run_options": [],
        "checks": ["python3-cli", "python3-metadata"],
        "disabled_tests": _DISABLED_SCHEDULER,
        "executors": ["scheduler"],
    },
    {
        "name": "python3-sfn",
        "disabled": False,
        "disable_parallel": True,
        "scheduler": "step-functions",
        "scheduler_timeout": 600,
        "python": "python3",
        "env": {
            "METAFLOW_USER": "tester",
            "METAFLOW_RUN_BOOL_PARAM": "False",
            "METAFLOW_RUN_NO_DEFAULT_PARAM": "test_str",
            "METAFLOW_DEFAULT_METADATA": "service",
            "METAFLOW_SERVICE_URL": "http://localhost:8080",
            "METAFLOW_DEFAULT_DATASTORE": "s3",
            "METAFLOW_DATASTORE_SYSROOT_S3": "s3://metaflow-test/metaflow/{nonce}",
            "METAFLOW_BATCH_JOB_QUEUE": "localbatch-default",
            "METAFLOW_BATCH_CLIENT_PARAMS": '{"endpoint_url":"http://localhost:8000"}',
            "METAFLOW_SFN_CLIENT_PARAMS": '{"endpoint_url":"http://localhost:8082"}',
            "METAFLOW_SFN_DYNAMO_DB_CLIENT_PARAMS": '{"endpoint_url":"http://localhost:8765"}',
            "METAFLOW_SFN_DYNAMO_DB_TABLE": "metaflow-sfn",
            "METAFLOW_SFN_IAM_ROLE": "arn:aws:iam::123456789012:role/sfn-local-role",
            "AWS_ACCESS_KEY_ID": "rootuser",
            "AWS_SECRET_ACCESS_KEY": "rootpass123",
            "AWS_ENDPOINT_URL_S3": "http://localhost:9000",
            "AWS_DEFAULT_REGION": "us-east-1",
        },
        "top_options": [
            "--metadata=service",
            "--event-logger=nullSidecarLogger",
            "--no-pylint",
            "--quiet",
            "--with=batch",
            "--datastore=s3",
        ],
        "run_options": [],
        "checks": ["python3-cli", "python3-metadata"],
        "disabled_tests": _DISABLED_CLOUD,
        "executors": ["scheduler"],
    },
]

CHECKS = {
    "python3-cli": {"python": "python3", "class": "CliCheck"},
    "python3-metadata": {"python": "python3", "class": "MetadataCheck"},
}

# Short pytest marker name for each context
CONTEXT_MARKERS = {
    "python3-all-local": "local",
    "python3-all-local-azure-storage": "azure",
    "python3-all-local-gcs": "gcs",
    "python3-batch": "batch",
    "python3-k8s": "k8s",
    "python3-argo-workflows": "argo",
    "python3-sfn": "sfn",
}
