name: pr-datastore-tests

on:
  push:
    branches:
    - master
  pull_request_target:
    types:
      - opened
      - synchronize
      - labeled

jobs:
  test_data:
    if: (github.event.action == 'labeled' && (github.event.label.name == 'approved' || github.event.label.name == 'ok-to-test')) || (github.event.action != 'labeled' && (contains(github.event.pull_request.labels.*.name, 'ok-to-test') || contains(github.event.pull_request.labels.*.name, 'approved')))
    name: S3 data tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        ref: refs/pull/${{ github.event.pull_request.number }}/merge
        submodules: recursive
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: Install Python 3.x dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install tox numpy pytest click boto3 requests pylint pytest-benchmark
    - name: Execute Data tests
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        METAFLOW_S3_TEST_ROOT: ${{ secrets.METAFLOW_S3_TEST_ROOT }}
      run: |
        cd test/data
        PYTHONPATH=$(pwd)/../../ python3 -m pytest --benchmark-skip -x -s -v
